package ch12_exception;

public class ExceptionMain {
	public static void main(String[] args) {
		System.out.println("메인 시작!");
		int[] arr = {1,2,3};
		System.out.println(arr[3]);
	}
}
